name: CI-Python

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7      
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies and run test
        run: |
          cd python-code
          pipenv install --dev      
          pipenv run pytest